In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
arr.shape

[1 2 3 4]
<class 'numpy.ndarray'>


(4,)

In [3]:
arr2=np.array([[1,2,3],[1,2,3]])
print(arr2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
arr3=np.array([1,2,3],dtype='float')
print(arr3)
print(arr3.dtype)

[[1 2 3]
 [1 2 3]]
(2, 3)
int64
2
[1. 2. 3.]
float64


In [4]:
v="DataScience"
arr4=np.fromiter(v,dtype='U1')
print(arr4)
print(arr4.ndim)
print(arr4.shape)

['D' 'a' 't' 'a' 'S' 'c' 'i' 'e' 'n' 'c' 'e']
1
(11,)


In [5]:
ar=np.arange(1,10,2,dtype="u1")
ar

array([1, 3, 5, 7, 9], dtype=uint8)

In [6]:
print(np.linspace(1,10,3))


[ 1.   5.5 10. ]


In [7]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'C')

array([[        -1, 2146435071,         -1],
       [  -1048577,          0, 1073741824],
       [         0, 1018167296,          0],
       [   1048576,          1,          0]], dtype=int32)

In [8]:
np.ones((3,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.add(a, b)
print(res)

[  7  77  23 130]


In [11]:
res2=np.subtract(a,b)
res2
np.multiply(a,b)
np.divide(a,b)
np.power(a,b)
np.mod(a,b)
np.remainder(a,b)
np.floor_divide(a,b)
np.absolute(a)
np.sqrt(a)
np.exp(a)
np.log(a)
np.sin(a)
np.cos(a)

array([ 0.28366219, -0.96725059,  0.90744678,  0.86231887])

In [12]:
a = np.array([5, 72, 13, 100])
b = 10
res=a+b
print(res)

[ 15  82  23 110]


In [13]:
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res=a+b
res

array([[ 3,  7, 11],
       [ 9, 13, 17]])

In [14]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res=np.where(a>18,b[0],b[1])
res

array(['Minor', 'Adult', 'Adult', 'Adult', 'Adult', 'Adult'], dtype='<U5')

In [15]:
a = np.array([10, 25, 40, 60])
conditions = [a < 20, a < 50, a >= 50]
choices = ["Low", "Medium", "High"]
res = np.select(conditions, choices,default="Unknown")
print(res)

['Low' 'Medium' 'Medium' 'High']


In [16]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
res=arr.reshape(3,4)
res.flatten()
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.var())
print(np.median(arr))

78
6.5
3.452052529534663
11.916666666666666
6.5


In [17]:
np.random.rand(9)

array([0.90621751, 0.50662199, 0.94190838, 0.15603715, 0.27978416,
       0.77463661, 0.98609791, 0.86325498, 0.56968236])

In [18]:
np.random.randint(1,10,size=9)

array([1, 5, 7, 9, 1, 5, 6, 8, 1], dtype=int32)

In [19]:
np.random.randn(3)

array([ 2.21179793, -0.8694581 ,  0.38307441])

In [20]:
np.random.seed(2)
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])

In [21]:
# Dataset (rows = students, cols = subjects)
marks = np.array([
    [90, 85, 88],
    [78, 82, 80],
    [92, 89, 94],
    [60, 70, 65]
])
# Average per student
avg = np.mean(marks, axis=1)
# Highest marks
highest = np.max(marks)
# Pass/Fail (pass if avg >= 75)
result = avg >= 75
print("Average:", np.round(avg,2))
print("Highest:", highest)
print("Pass/Fail:", result)

Average: [87.67 80.   91.67 65.  ]
Highest: 94
Pass/Fail: [ True  True  True False]


In [22]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[5 7 9]
[ 6 15]


In [25]:
col=np.array([[1],[2],[3]])
row=np.array([10,20,30])
print(col+row)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [27]:
print(np.argmax(col))
print(np.argmin(row))

2
0


In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a,b)))
print(np.vstack((a,b)))
print(np.concatenate((a, b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [37]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [41]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(np.hsplit(matrix, 2))
print(np.vsplit(matrix, 2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [46]:
arr = np.array([10, 20, 30, 40, 50])
np.random.shuffle(arr)
print(arr)

[20 10 30 50 40]


In [58]:
arr = np.array([1, 2, 3, 4])
np.random.permutation(arr)
print(arr)

[1 2 3 4]


In [56]:
data = np.array([5, 12, 18, 25, 30])
mask = data > 15
print(mask)
print(data[mask])

[False False  True  True  True]
[18 25 30]


In [57]:
import numpy as np
import time
arr = np.arange(1_000_000)
start = time.time()
result1 = []
for x in arr:
    result1.append(x * 2)
end = time.time()
print("Python loop time:", end - start)
start = time.time()
result2 = arr * 2
end = time.time()
print("NumPy vectorized time:", end - start)

Python loop time: 0.3767378330230713
NumPy vectorized time: 0.004444599151611328


In [62]:
arr=np.array([10, 20, 30, 40])
arr1=np.array([[1, 2],
               [3, 4]])
print(arr)
print(arr1)
print(arr[-1])

[10 20 30 40]
[[1 2]
 [3 4]]
40


In [69]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,9])
print(a+b)
print(np.add(a,b))
print(a*2)
print(np.multiply(a,b))
print(a**2)

[ 6  8 10 13]
[ 6  8 10 13]
[2 4 6 8]
[ 5 12 21 36]
[ 1  4  9 16]


In [72]:
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
res=a+b
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [78]:
arr=np.array([10, 20, 30, 40])
arr1=np.array([[1,2,3],
 [4,5,6]])
print(arr.mean())
print(arr.sum())
print(arr1.mean(axis=0))

25.0
100
[2.5 3.5 4.5]


In [82]:
arr=np.array([1,2,3,4,5,6])
a=arr.reshape(2,3)
print(a)
a.flatten()
arr+10

[[1 2 3]
 [4 5 6]]


array([11, 12, 13, 14, 15, 16])

In [89]:
a=np.array([5, 15, 8, 20])
print(a[a>15])
a[a<10]=0
print(a)
np.where(a>10)

[20]
[ 0 15  0 20]


(array([1, 3]),)

In [92]:
np.random.seed(1)
np.random.rand(3)
np.random.randint(1,10,(2,2))

array([[6, 1],
       [1, 2]], dtype=int32)

In [94]:
a=np.array([1,2])
b=np.array([3,4])
print(np.dot(a,b))

11


In [95]:
a=np.array([[1,2],
            [3,4]] )
b=np.array( [[5,6],
             [7,8]])
print(np.matmul(a,b))

[[19 22]
 [43 50]]


In [97]:
a = np.array([1, 2, 3])
b = 0
print(a / b)

[inf inf inf]


C:\Users\saisu\AppData\Local\Temp\ipykernel_4076\1225741237.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a / b)
